dist: trusty
sudo: required
language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
    - $(npm config get prefix)/bin/ganache-cli
before_install:
  - npm install -g npx
script:
  - ./scripts/setup-ci.sh
  - npm run lint
  - npm run test
  - npx frg-coverage
after_success:
  - cat coverage/lcov.info | npx coveralls
notifications:
  email:
    - dev-support@ampleforth.org
  slack: fragmentsorg:2bN0L0FCZZ0illBRyPucRZkV
